### ISSUE TITLE
Customization for the JGS542E

### ISSUE THREAD

**Issue by mapo-89** [ckarrie/ha-netgear-plus#14]
Is it possible to customize the integration so that it also works for the JGS542E

**Comment by ckarrie** [comment]
I need help impleneting this, because I don't have a JGS542E for testing

**Comment by mapo-89** [comment]
What exactly do you need from me?

**Comment by ckarrie** [comment]
I think its a JGS5**24**E, right? I hope its a v2 Version, [otherwise it won't work](https://community.netgear.com/t5/Plus-and-Smart-Switches-Forum/JGS524E-Not-V2-Web-Interface-Unavailable/m-p/2223615/highlight/true#M20883)

Let's cross fingers to not invent the wheel again :-)

- Go to the Web UI of the device and analyze the traffic, here is a [very good example](https://github.com/ckarrie/ckw-ha-gs108e/issues/12#issuecomment-1514437137) that helped me
- Output of the devices `login.cgi` (not logged in) to detect the Netgear Switch Model (Model Name)
- Now Login
- Output of `switch_info.cgi` (Bootloader and/or Firmware and often a hidden input field called `hash` )
- Output of `portStatistics.cgi` (Traffic on each port)

Thank you

**Comment by ckarrie** [comment]
Edit: but there are ways maybe :-) https://github.com/tabacha/ProSafeLinux

**Comment by mapo-89** [comment]
Yes it is a JGS524Ev2
Ther is no `login.cgi`, but a login.htm with code below:
[login.txt](https://github.com/user-attachments/files/16014441/login.txt)

Also the `switch_info.cgi` isn't available, but `status_switch_info.htm`
[status_switch_info.txt](https://github.com/user-attachments/files/16014948/switch_info.txt)

`portStatistics.cgi` isn't available as well, but `monitoring_port_statistics.htm`
[monitoring_port_statistics.txt](https://github.com/user-attachments/files/16014985/monitoring_port_statistics.txt)

**Comment by ckarrie** [comment]
Thank you, in your `login.txt` I found following line in the head/script block:

```javascript
var sysGeneInfor = 'JGS524Ev2?Rack?**:**:**:**:**:**?2.6.0.48?Enable?192.**.**.**?255.255.255.0?192.**.**.**?*******';
                                   ^ Model Name     ^ MAC                     ^ Firmware  ^ ?  ^ IP                 ^ Netmask        ^ Gateway     ^ ?
```

did you blacklisted the (I guess) MAC, IP, Gateway?  I can't guess the last.

I could [parse that variable](https://stackoverflow.com/questions/18368058/how-can-i-parse-javascript-variables-using-python) and get the model and firmware version out of that string.

**Comment by mapo-89** [comment]
the last one is the serial number

**Comment by mapo-89** [comment]
how is the progress here? Do you still need support

**Comment by foxey** [comment]
Hi @mapo-89, I was planning to start the implementation, but I'm stuck with the login function.
Did you make any more changes to the login.txt page except for the MAC address and serial number?

`var md5Key   = "YOU_CAN_NOT_PASS";` Is this from the switch or did you change that as well?

**Comment by mapo-89** [comment]
Hi @foxey,
the only thing I've blurred is the sysGeneInfor variable. as ckarrie already mentioned, it is correct

> Thank you, in your `login.txt` I found following line in the head/script block:
> 
> var sysGeneInfor = 'JGS524Ev2?Rack?**:**:**:**:**:**?2.6.0.48?Enable?192.**.**.**?255.255.255.0?192.**.**.**?*******';
>                     ^ Model Name   ^ MAC             ^ Firmware  ^ ? ^ IP         ^ Netmask     ^ Gateway     ^ ?
> did you blacklisted the (I guess) MAC, IP, Gateway? I can't guess the last - but we only need Model and Firmware now, so it's fine.
> ...

**Comment by mapo-89** [comment]
The Request:
submitId: pwdLogin
password: 26fe7cce1e480dd05e7f76155579d3ed
submitEnd: 

ResponseCookie:
MmcYWOKlaJDyXC8T2NRsDK73gHFoNxR

RequestCookie:
O9O66elq0cpbH22QUVvVN6a0GpX6crM

**Comment by foxey** [comment]
@mapo-89 Thanks! I actually need the Name of the cookie instead of the value (SID in my screenshot).

**Comment by mapo-89** [comment]
I get the following error

I think the problem is that in this case there is no `login.cgi` in this case, only the `login.htm`


`ngp-cli -dv identify 192.168.xxx.xxx`
>Enabling debug mode.
DEBUG:py_netgear_plus.parsers:PageParser object initialized.
DEBUG:py_netgear_plus:[NetgearSwitchConnector] instance (v0.4.1rc0) created for IP=192.168.xxx.xxx
DEBUG:py_netgear_plus:[NetgearSwitchConnector] DEBUG logging enabled. Your logs may contain sensitve information like passwords or session cookies. Do not use in production.
DEBUG:py_netgear_plus:[NetgearSwitchConnector.autodetect_model] called for IP=192.168.xxx.xxx
DEBUG:py_netgear_plus.fetcher:[PageFetcher.request] calling GET http://192.168.xxx.xxx/login.cgi without cookie with params=None, allow_redirects=False, timeout=15
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 192.168.xxx.xxx:80
DEBUG:urllib3.connectionpool:http://192.168.xxx.xxx:80 "GET /login.cgi HTTP/1.1" 404 None
Traceback (most recent call last):
  File "...\venv\Lib\site-packages\urllib3\response.py", line 754, in _error_catcher
    yield
  File "...\venv\Lib\site-packages\urllib3\response.py", line 879, in _raw_read
    data = self._fp_read(amt, read1=read1) if not fp_closed else b""
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\venv\Lib\site-packages\urllib3\response.py", line 862, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
           ^^^^^^^^^^^^^^^^^^
  File "...\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\http\client.py", line 473, in read
    s = self.fp.read(amt)
        ^^^^^^^^^^^^^^^^^
  File "...\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] An existing connection was closed by the remote host

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "...\venv\Lib\site-packages\requests\models.py", line 820, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "...\venv\Lib\site-packages\urllib3\response.py", line 1066, in stream
    data = self.read(amt=amt, decode_content=decode_content)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\venv\Lib\site-packages\urllib3\response.py", line 955, in read
    data = self._raw_read(amt)
           ^^^^^^^^^^^^^^^^^^^
  File "...\venv\Lib\site-packages\urllib3\response.py", line 878, in _raw_read
    with self._error_catcher():
  File "...\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "...\venv\Lib\site-packages\urllib3\response.py", line 781, in _error_catcher
    raise ProtocolError(f"Connection broken: {e!r}", e) from e
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(10054, 'An existing connection was closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "...\venv\Scripts\ngp-cli.exe\__main__.py", line 7, in <module>
  File "...\venv\Lib\site-packages\py_netgear_plus\ngp_cli.py", line 131, in main
    command_chooser(args, command_functions)
  File "...\venv\Lib\site-packages\py_netgear_plus\ngp_cli.py", line 229, in command_chooser
    command_functions[args.command](connector, args)
  File "...\venv\Lib\site-packages\py_netgear_plus\ngp_cli.py", line 281, in identify_command
    model = connector.autodetect_model()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\venv\Lib\site-packages\py_netgear_plus\__init__.py", line 124, in autodetect_model
    response = self._page_fetcher.request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\venv\Lib\site-packages\py_netgear_plus\fetcher.py", line 304, in request
    response = requests.request(method, url, **kwargs)  # noqa: S113
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\venv\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\venv\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\venv\Lib\site-packages\requests\sessions.py", line 746, in send
    r.content
  File "...\venv\Lib\site-packages\requests\models.py", line 902, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\venv\Lib\site-packages\requests\models.py", line 822, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(10054, 'An existing connection was closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was closed by the remote host', None, 10054, None))

**Comment by mapo-89** [comment]
I also get a 404 back via browser. Nevertheless, the browser tries to continue loading. I suspect that the browser gets a ConnectionReset after a timeout.

**Comment by foxey** [comment]
Hi @mapo-89, I've created a new version that catches the connection reset. Can you give it another try?
Additionally, if the login fails, can you provide me the exact **URL** that the UI posts the login form to and also the **name of the cookie** (**SID** for the GS308EP).

```bash
python -mvenv venv
. ./venv/bin/activate
pip install py-netgear-plus==0.4.1rc1
ngp-cli -dv identify SWITCH_IP_ADDRESS
ngp-cli -dvP YOUR_PASSWORD login SWITCH_IP_ADDRESS
ngp-cli -dv logout
```

**Comment by mapo-89** [comment]
OK, the identify command works and returns the correct switch device name. Unfortunately, the login does not yet work.

The **URL** is http://192.168.xxx.xxx/login.htm and the name of the cookie is also **SID**

**Comment by mapo-89** [comment]
ngp-cli -dvP Password1 login 192.168.xxx.xxx

>Enabling debug mode.
DEBUG:py_netgear_plus.parsers:PageParser object initialized.
DEBUG:py_netgear_plus:[NetgearSwitchConnector] instance (v0.4.1rc1) created for IP=192.168.xxx.xxx
DEBUG:py_netgear_plus:[NetgearSwitchConnector] DEBUG logging enabled. Your logs may contain sensitve information like passwords or session cookies. Do not use in production.
DEBUG:py_netgear_plus:[NetgearSwitchConnector.autodetect_model] called for IP=192.168.xxx.xxx
DEBUG:py_netgear_plus.fetcher:[PageFetcher.request] calling GET http://192.168.xxx.xxx/login.cgi without cookie with params=None, allow_redirects=False, timeout=15
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 192.168.xxx.xxx:80
DEBUG:urllib3.connectionpool:http://192.168.xxx.xxx:80 "GET /login.cgi HTTP/1.1" 404 None
DEBUG:py_netgear_plus.fetcher:[PageFetcher.request] calling GET http://192.168.xxx.xxx/login.htm without cookie with params=None, allow_redirects=False, timeout=15
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 192.168.xxx.xxx:80
DEBUG:urllib3.connectionpool:http://192.168.xxx.xxx:80 "GET /login.htm HTTP/1.1" 200 None
DEBUG:py_netgear_plus.parsers:[PageParser.parse_login_form_rand] rand INPUT element not found.
DEBUG:py_netgear_plus.parsers:[PageParser.parse_login_title_tag] TITLE element not found.
DEBUG:py_netgear_plus.parsers:[PageParser.parse_login_form_rand] rand INPUT element not found.
DEBUG:py_netgear_plus.parsers:[PageParser.parse_login_title_tag] TITLE element not found.
DEBUG:py_netgear_plus.parsers:[PageParser.parse_login_form_rand] rand INPUT element not found.
DEBUG:py_netgear_plus.parsers:[PageParser.parse_login_title_tag] TITLE element not found.
DEBUG:py_netgear_plus.parsers:[PageParser.parse_login_switchinfo_tag] DIV with class 'switchInfo' not found.
DEBUG:py_netgear_plus.parsers:[PageParser.parse_login_form_rand] rand INPUT element not found.
DEBUG:py_netgear_plus.parsers:[PageParser.parse_login_title_tag] TITLE element not found.
DEBUG:py_netgear_plus.parsers:[PageParser.parse_login_switchinfo_tag] DIV with class 'switchInfo' not found.
DEBUG:py_netgear_plus.parsers:[PageParser.parse_login_form_rand] rand INPUT element not found.
DEBUG:py_netgear_plus.parsers:[PageParser.parse_login_form_rand] rand INPUT element not found.
DEBUG:py_netgear_plus.parsers:[PageParser.parse_login_title_tag] TITLE element not found.
DEBUG:py_netgear_plus.parsers:[PageParser.parse_login_form_rand] rand INPUT element not found.
DEBUG:py_netgear_plus.parsers:[PageParser.parse_login_title_tag] TITLE element not found.
DEBUG:py_netgear_plus.parsers:[PageParser.parse_login_form_rand] rand INPUT element not found.
DEBUG:py_netgear_plus.parsers:[PageParser.parse_login_title_tag] TITLE element not found.
DEBUG:py_netgear_plus.parsers:[PageParser.parse_login_form_rand] rand INPUT element not found.
DEBUG:py_netgear_plus.parsers:[PageParser.parse_login_title_tag] TITLE element not found.
DEBUG:py_netgear_plus.parsers:[PageParser.parse_login_form_rand] rand INPUT element not found.
DEBUG:py_netgear_plus.parsers:[PageParser.parse_login_title_tag] TITLE element not found.
DEBUG:py_netgear_plus.parsers:[PageParser.parse_login_form_rand] rand INPUT element not found.
DEBUG:py_netgear_plus.parsers:[PageParser.parse_login_title_tag] TITLE element not found.
INFO:py_netgear_plus:[NetgearSwitchConnector.autodetect_model] found JGS524Ev2 switch.
DEBUG:py_netgear_plus.parsers:JGS524Ev2 object initialized.
DEBUG:py_netgear_plus.fetcher:[PageFetcher.check_login_url] calling request for GET http://192.168.xxx.xxx/login.cgi with allow_directs=False, timeout=15
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 192.168.xxx.xxx:80
DEBUG:urllib3.connectionpool:http://192.168.xxx.xxx:80 "GET /login.cgi HTTP/1.1" 404 None
Traceback (most recent call last):
  File "...\venv\Lib\site-packages\urllib3\response.py", line 754, in _error_catcher
    yield
  File "...\venv\Lib\site-packages\urllib3\response.py", line 879, in _raw_read
    data = self._fp_read(amt, read1=read1) if not fp_closed else b""
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "...\venv\Lib\site-packages\urllib3\response.py", line 862, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
           ~~~~~~~~~~~~~^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.496.0_x64__qbz5n2kfra8p0\Lib\http\client.py", line 479, in read
    s = self.fp.read(amt)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.496.0_x64__qbz5n2kfra8p0\Lib\socket.py", line 719, in readinto
    return self._sock.recv_into(b)
           ~~~~~~~~~~~~~~~~~~~~^^^
ConnectionResetError: [WinError 10054] An existing connection was closed by the remote host

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "...\venv\Lib\site-packages\requests\models.py", line 820, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "...\venv\Lib\site-packages\urllib3\response.py", line 1066, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "...\venv\Lib\site-packages\urllib3\response.py", line 955, in read
    data = self._raw_read(amt)
  File "...\venv\Lib\site-packages\urllib3\response.py", line 878, in _raw_read
    with self._error_catcher():
         ~~~~~~~~~~~~~~~~~~~^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.496.0_x64__qbz5n2kfra8p0\Lib\contextlib.py", line 162, in __exit__
    self.gen.throw(value)
    ~~~~~~~~~~~~~~^^^^^^^
  File "...\venv\Lib\site-packages\urllib3\response.py", line 781, in _error_catcher
    raise ProtocolError(f"Connection broken: {e!r}", e) from e
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(10054, 'An existing connection was closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "...\venv\Scripts\ngp-cli.exe\__main__.py", line 7, in <module>
    sys.exit(main())
             ~~~~^^
  File "...\venv\Lib\site-packages\py_netgear_plus\ngp_cli.py", line 131, in main
    command_chooser(args, command_functions)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\venv\Lib\site-packages\py_netgear_plus\ngp_cli.py", line 229, in command_chooser
    command_functions[args.command](connector, args)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "...\venv\Lib\site-packages\py_netgear_plus\ngp_cli.py", line 293, in login_command
    if connector.get_login_cookie() and save_cookie(connector):
       ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "...\venv\Lib\site-packages\py_netgear_plus\__init__.py", line 243, in get_login_cookie
    self._page_fetcher.check_login_url(self.switch_model)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "...\venv\Lib\site-packages\py_netgear_plus\fetcher.py", line 111, in check_login_url
    self._login_page_response = requests.request(
                                ~~~~~~~~~~~~~~~~^
        "get", url, allow_redirects=allow_redirects, timeout=timeout
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "...\venv\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\venv\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "...\venv\Lib\site-packages\requests\sessions.py", line 746, in send
    r.content
  File "...\venv\Lib\site-packages\requests\models.py", line 902, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
                    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\venv\Lib\site-packages\requests\models.py", line 822, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(10054, 'An existing connection was closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was closed by the remote host', None, 10054, None))

**Comment by foxey** [comment]
Unfortunately, the login doesn't work yet: the switch doesn't send the SID cookie back, but instead a redirect to the login page. There can be two reasons for this:
1. The password hash is wrong (did you use the temporary password 'Password1'? I that case I can rule that out).
2. The switch rejects the login attempt, because I omitted the empty 'submitEnd:' parameter.

**Comment by mapo-89** [comment]
yes it's the Password1 password

**Comment by foxey** [comment]
I've added the 'submitEnd' parameter in the form data. Could you retest?
`pip install py-netgear-plus==0.4.2rc1`

The only difference between the web UI form post and the Python library is now the order of the parameters. According to the HTTP specification, that should not have any impact, but given the peculiar implementation of NETGEAR, nothing surprises me anymore. To change that I need to hard-code it and that makes the code on the long run less maintainable, so I'd like to avoid that if possible.

**Comment by foxey** [comment]
Frustrating! Let's take another approach.
Can you execute this snippet in Python and share the output:
```python
import requests

ip="YOUR_IP"

data = {
    "password": "26fe7cce1e480dd05e7f76155579d3ed",
    "submitId": "pwdLogin",
    "submitEnd": ""
}

url = "http://{ip}/login.cgi".format(ip=ip)

response = requests.request("post", url, data=data, timeout=15, allow_redirects=False)

print ("response.status_code=", response.status_code)
print("\nresponse.content:")
print(response.content.decode("utf8"))

print("\nresponse.cookies:")
print(response.cookies)

data = {
    "submitId": "pwdLogin",
    "password": "26fe7cce1e480dd05e7f76155579d3ed",
    "submitEnd": ""
}

response = requests.request("post", url, data=data, timeout=15, allow_redirects=False)

print ("response.status_code=", response.status_code)
print("\nresponse.content:")
print(response.content.decode("utf8"))

print("\nresponse.cookies:")
print(response.cookies)
```

**Comment by mapo-89** [comment]
response.status_code= 200

response.content:
<html><body><script language=JavaScript>
location.href='/login.htm'
</script></body></html>


response.cookies:
<RequestsCookieJar[]>
response.status_code= 200

response.content:
<html><body><script language=JavaScript>
location.href='/index.htm?0'
</script></body></html>


response.cookies:
<RequestsCookieJar[<Cookie SID=pTVAfglJ2sZibN8naxY1ZaGjtfauWRr for 192.168.xxx.xxx/>]>

**Comment by foxey** [comment]
Hurray! What a mess. I'll try to find an elegant way to define the order of the parameters in the library. From there on, it should be fairly straightforward (famous last words 😬).

**Comment by mapo-89** [comment]
> Hurray! What a mess. I'll try to find an elegant way to define the order of the parameters in the library. From there on, it should be fairly straightforward (famous last words 😬).
> 
> PS does the last call (with submitEnd: None) also work?

No, it only works with `""`

**Comment by foxey** [comment]
@mapo-89 the login should now work in py-netgear-plus==v0.4.2rc3. Can you validate that?

I started parsing the pages, but I miss some info:
- a copy of the page with the port status (CONNECTED/AVAILABLE, 10/100/1000Mb, etc.)
- the exact calls to these pages (POST/GET and the parameters, just like for the login*):
  - status_switch_info.htm
  - monitoring_port_statistics.htm
  - the port status page
 
*) There's a variable `secureRand` in the status_switch_info. I expect that the calls to monitoring_port_statistics.htm and the port status pages are POST calls with this parameter, but it could also be a GET with this variable as query string.

**Comment by mapo-89** [comment]
Yes the login was successful.

I'll write you the requests in Python here, maybe it's a bit clearer. The corresponding pages are attached in the appendix.

**Port Status Page:**
```python
url = "http://192.168.xxx.xxx/config/status_status.htm"

payload = {}
headers = {
      'Cookie': 'SID=7gHD6FrYcAsvqvoB9wstgSha60EPTPA'
}

response = requests.request("GET", url, headers=headers, data=payload)
```

**Status Switch Info**
```python
url = "http://192.168.xxx.xxx/config/status_switch_info.htm"

payload = {}
headers = {
      'Cookie': 'SID=7gHD6FrYcAsvqvoB9wstgSha60EPTPA'
}

response = requests.request("GET", url, headers=headers, data=payload)
```

**Monitoring Port Statistics**
```python
url = "http://192.168.xxx.xxx/config/monitoring_port_statistics.htm"

payload = {}
headers = {
      'Cookie': 'SID=7gHD6FrYcAsvqvoB9wstgSha60EPTPA'
}

response = requests.request("GET", url, headers=headers, data=payload)
```

It seems that the variable `secureRand

 ` is a JavaScript variable that is used for the actual POST forms. However, nothing is sent with the GET requests and it also seems as if the SID cookie is sufficient to get the response.

[JGS542 pages.zip](https://github.com/user-attachments/files/18538900/JGS542.pages.zip)

**Comment by foxey** [comment]
Thanks! At last something less complicated than expected 🙂. I'll complete the parser and have you test the status call next.

**Comment by foxey** [comment]
@mapo-89 I think we're (almost) there. v0.4.2rc5 contains the full parser.
You can test with:
```python
python -mvenv venv
. ./venv/bin/activate  # or in Windows: \venv\Scripts\activate.bat
pip install py-netgear-plus==v0.4.2rc5
ngp-cli -dv identify SWITCH_IP_ADDRESS
ngp-cli -dvP YOUR_PASSWORD login SWITCH_IP_ADDRESS
ngp-cli -dv status
ngp-cli -dv logout
```

There is one other detail: I parse the interface statistics as Received (rx), Transmitted (tx), Errors (crc), but I don't know if this is correct. Could you check if it is the correct order?

**Comment by foxey** [comment]
Released in [v0.7.4](https://github.com/ckarrie/ha-netgear-plus/releases/tag/v0.7.4).

**Comment by mapo-89** [comment]
ngp-cli -dv status

```python
DEBUG:urllib3.connectionpool:http://192.168.xxx.xxx:80 "GET /status_switch_info.htm HTTP/1.1" 404 None
DEBUG:py_netgear_plus:NetgearSwitchConnector.fetch_page: caught PageFetcherConnectionError
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "...\venv\Scripts\ngp-cli.exe\__main__.py", line 7, in <module>
    sys.exit(main())
             ~~~~^^
  File "...\venv\Lib\site-packages\py_netgear_plus\ngp_cli.py", line 131, in main
    command_chooser(args, command_functions)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\venv\Lib\site-packages\py_netgear_plus\ngp_cli.py", line 229, in command_chooser
    command_functions[args.command](connector, args)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "...\venv\Lib\site-packages\py_netgear_plus\ngp_cli.py", line 341, in status_command
    switch_infos = connector.get_switch_infos()
  File "...\venv\Lib\site-packages\py_netgear_plus\__init__.py", line 388, in get_switch_infos
    self._get_switch_metadata()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "...\venv\Lib\site-packages\py_netgear_plus\__init__.py", line 433, in _get_switch_metadata
    page = self.fetch_page_from_templates(self.switch_model.SWITCH_INFO_TEMPLATES)
  File "...\venv\Lib\site-packages\py_netgear_plus\__init__.py", line 377, in fetch_page_from_templates
    raise PageNotLoadedError(message)
py_netgear_plus.fetcher.PageNotLoadedError: Failed to load any page of templates: [{'method': 'get', 'url': 'http://{ip}/status_switch_info.htm'}]

**Comment by foxey** [comment]
Oh, shoot, I didn´t see the `config/` prefix in the URL...
Let me fix that.

**Comment by mapo-89** [comment]
looks good, 
also the order of the statistics
