### ISSUE TITLE
GS108PEv3

### ISSUE THREAD

**Issue by Megachip** [ckarrie/ha-netgear-plus#23]
```
2024-08-27 19:30:17.317 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 456, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 537, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 366, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 413, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 516, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ckw_hass_gs108e/config_flow.py", line 127, in async_step_user
    unique_id = await self.hass.async_add_executor_job(api.get_unique_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ckw_hass_gs108e/gs108e/__init__.py", line 210, in get_unique_id
    raise MissingSwitchModel
custom_components.ckw_hass_gs108e.gs108e.MissingSwitchModel
```
Firmware and Webinterface looking exCTLY THE SAME LIKE ON GS108E - so maybe it just need to accept the model.
Seems there are no poe options or informations :(

**Comment by foxey** [comment]
@Megachip GS108Ev3 is in the list of supported models now. Can you confirm it works?

**Comment by Megachip** [comment]
> @Megachip GS108Ev3 is in the list of supported models now. Can you confirm it works?

Have to recheck. After updating 0.6.1 to 0.6.4 it still showing 0.6.1 ... either someone forget to increment the version number or there was an issue on updating ;)

**Comment by Megachip** [comment]
Loginpage:
```
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<link rel="stylesheet" type="text/css" href="login.css?v3.e">
<title>NETGEAR GS108PEv3</title>
<script src="login.js?v3.e" type="text/javascript"></script>
<script src="jquery.md5.js" type="text/javascript"></script>
<script language="JavaScript">
function submitLogin()
{
    encryptPwd();
	document.forms[0].submit();
	return true;
}
function showErrmsg()
{
	var errMsg = document.getElementById("err_msg");
	var errDiv = document.getElementById("pwdErr");

	if (errMsg.value != "")
	{
		errDiv.innerHTML = errMsg.value;
	}
	else
	{
		errDiv.innerHTML = "";
	}
}
</script>
</head>
<body onload="init();showErrmsg();changeLoginButtonStyle();">
<div id="mainArea" class="mainArea">
  <div id="mainTitleArea" class="mainTitleArea">
   <img class="customGraph" src="NgrLogo.png">
   <img class="factGraph" src="ContentVisual.png">
   <div class="switchInfo">GS108PEv3 - 8-Port Gigabit Ethernet Smart Managed Plus Switch</div>
  </div>
  <div id="loginContainer" class="loginContainer">
   <form method="post" action="login.cgi" name="login" autocomplete="off" onSubmit="return false;" >
    <input type="hidden" id="submitPwd" name="password" value="">
    <div id="contentArea">
	 <div id="loginArea" class="loginArea">
	  <div id="loginTitleArea">
	   <table>
		<tr>
		<script>tbhdrLoginTable('Anmeldung');</script>
		</tr>
		<tr>
		 <td></td>
		 <td colspan="2">
		  <table>
		   <tr>
		    <td class="topLoginTitleBottomBar"></td>
		   </tr>
		  </table>
		 </td>
		 <td></td>
		</tr>
	   </table>
	  </div>
	  <div id="loginBlkbArea" class="bClass">
	   <div id="loginDiv" class="loginBox">
	    <div id="loginTDataArea" class="tableData mTop25">
	     <table id="loginTData">
	      <tbody>
	       <tr>
		  <td width="23px"><div></div></td>
		  <td width="100px">
		   <div class="colInterval textLeft">Passwort</div>
		  </td>
		  <td width="290px">
		   <input id="password" class="textInputStyle textInputLength" type="password"  onkeypress="onEnterSub(event);" maxlength="20" style="border:1px #CCCCCC solid;">
		  </td>
		  <td width="23px"><div></div></td>
              </tr>
              <tr>
		  <td width="23px"><div></div></td>
		  <td width="100px"><div></div></td>
		  <td width="290px">
		   <div id="pwdErr" class="pwdErrStyle"></div>
		  </td>
		  <td width="23px"><div></div></td>
		</tr>
 			 <tr>
 			  <td width="23px"><div></div></td>
 			  <td width="100px"><div></div></td>
 			  <td width="290px">
				<a id="loginBtn" class="loginBtnStyle" href="javascript:submitLogin()">Anmeldung</a>
 			  </td>
 			  <td width="23px"><div></div></td>
 			 </tr>
 			</tbody>
 		   </table>
 		  </div></div></div></div></div>
		  <input type=hidden id="rand" name="rand" value='1735414426' disabled>
 		  <input type=hidden name='err_msg' id='err_msg' value='' disabled>
 		 </form>
 		</div>
         <div class="footerImg">
          <div class="copyrightGraphWrap">
           <span>&copy; NETGEAR, Inc. Alle Rechte vorbehalten.</span>
          </div>
          <img style="float:right;" src="Footer_Facet.png">
         </div>
  </div>
</body>
</html>
```
status.htm
```
<!DOCTYPE HTML>
<html>
<head>
<title>Port Status</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<link rel="stylesheet" type="text/css" href="style.css?v3.e">
<script  src="frame.js?v3.e" type="text/javascript"></script>
<script  src="function.js?v3.e" type="text/javascript"></script>
</head>
<body onload="initTableCss()">
<form method="post" action="status.cgi">
<table class="detailsAreaContainer">
<tr>
<td><table class="tableStyle">
<tr>
<script>tbhdrTable('Portstatus','portStatus')</script>
</tr>
<tr><td class="topTitleBottomBar" colspan="2"></td></tr>
<tr><td class="paddingTableBody" colspan="2"><table class="tableStyle" id="tbl2" style='width:600px;'>
<tr><td class="def_TH spacer4Percent def_center"><input type="checkbox" name="checkALL" rownumber="" value="notchecked" onclick="checkAllCheckedRows('portID')" /></td>
<td class="def_TH">Port</td>
<td class="def_TH spacer40Percent">Portstatus</td>
<td class="def_TH spacer22Percent">Geschwindigkeit</td>
<td class="def_TH spacer50Percent">Verbindungsgeschwindigkeit</td>
<td class="def_TH spacer22Percent">Flusssteuerung</td>
<td class="def_TH spacer22Percent">Max. MTU</td>
</tr>
<tr id="g_1_1" exclusive="">
    <td class="def_TH def_center"></td>
    <td class="def_TH" sel="text"></td>
    <td class="def_TH" sel="text"></td>
    <td class="def_TH" sel="select"><select name="SPEED" disabled>
        <option value="0"></option>
        <option value="1">Auto</option>
        <option value="2">Deaktiviert</option>
        <option value="3">10M halb</option>
        <option value="4">10M voll</option>
        <option value="5">100M halb</option>
        <option value="6">100M voll</option>
    </select>
    </td>
    <td class="def_TH" sel="text"></td>
    <td class="def_TH" sel="select"><select name="FLOW_CONTROL" disabled>
        <option value="0"></option>
        <option value="1">Aktiviert</option>
        <option value="2">Deaktiviert</option>
    </select>
    </td>
    <td class="def_TH" sel="text"></td>
</tr>


<tr class="portID"><td class="def firstCol def_center"><input class="checkbox" type="checkbox" name="port1" rownumber="" value="checked" onclick="checkBoxOnclick();"></td>
<td class="def firstCol" sel="text">1
<input type="hidden" value="1"></td>
<td class="def " sel="text">Inaktiv
<input type="hidden" value="Inaktiv"></td>
<td class="def " sel="select">Auto
<input type="hidden" value="1"></td>
<td class="def " sel="text">Nicht verbunden
<input type="hidden" value="Nicht verbunden"></td>
<td class="def " sel="select">Deaktiviert
<input type="hidden" value="2"></td>
<td class="def firstCol" sel="text">9702
<input type="hidden" value="9702"></td>

<tr class="portID"><td class="def firstCol def_center"><input class="checkbox" type="checkbox" name="port2" rownumber="" value="checked" onclick="checkBoxOnclick();"></td>
<td class="def firstCol" sel="text">2
<input type="hidden" value="2"></td>
<td class="def " sel="text">Inaktiv
<input type="hidden" value="Inaktiv"></td>
<td class="def " sel="select">Auto
<input type="hidden" value="1"></td>
<td class="def " sel="text">Nicht verbunden
<input type="hidden" value="Nicht verbunden"></td>
<td class="def " sel="select">Deaktiviert
<input type="hidden" value="2"></td>
<td class="def firstCol" sel="text">9702
<input type="hidden" value="9702"></td>

<tr class="portID"><td class="def firstCol def_center"><input class="checkbox" type="checkbox" name="port3" rownumber="" value="checked" onclick="checkBoxOnclick();"></td>
<td class="def firstCol" sel="text">3
<input type="hidden" value="3"></td>
<td class="def " sel="text">Inaktiv
<input type="hidden" value="Inaktiv"></td>
<td class="def " sel="select">Auto
<input type="hidden" value="1"></td>
<td class="def " sel="text">Nicht verbunden
<input type="hidden" value="Nicht verbunden"></td>
<td class="def " sel="select">Deaktiviert
<input type="hidden" value="2"></td>
<td class="def firstCol" sel="text">9702
<input type="hidden" value="9702"></td>

<tr class="portID"><td class="def firstCol def_center"><input class="checkbox" type="checkbox" name="port4" rownumber="" value="checked" onclick="checkBoxOnclick();"></td>
<td class="def firstCol" sel="text">4
<input type="hidden" value="4"></td>
<td class="def " sel="text">Inaktiv
<input type="hidden" value="Inaktiv"></td>
<td class="def " sel="select">Auto
<input type="hidden" value="1"></td>
<td class="def " sel="text">Nicht verbunden
<input type="hidden" value="Nicht verbunden"></td>
<td class="def " sel="select">Deaktiviert
<input type="hidden" value="2"></td>
<td class="def firstCol" sel="text">9702
<input type="hidden" value="9702"></td>

<tr class="portID"><td class="def firstCol def_center"><input class="checkbox" type="checkbox" name="port5" rownumber="" value="checked" onclick="checkBoxOnclick();"></td>
<td class="def firstCol" sel="text">5
<input type="hidden" value="5"></td>
<td class="def " sel="text">Aktiv
<input type="hidden" value="Aktiv"></td>
<td class="def " sel="select">Auto
<input type="hidden" value="1"></td>
<td class="def " sel="text">100M
<input type="hidden" value="100M"></td>
<td class="def " sel="select">Deaktiviert
<input type="hidden" value="2"></td>
<td class="def firstCol" sel="text">9702
<input type="hidden" value="9702"></td>

<tr class="portID"><td class="def firstCol def_center"><input class="checkbox" type="checkbox" name="port6" rownumber="" value="checked" onclick="checkBoxOnclick();"></td>
<td class="def firstCol" sel="text">6
<input type="hidden" value="6"></td>
<td class="def " sel="text">Aktiv
<input type="hidden" value="Aktiv"></td>
<td class="def " sel="select">Auto
<input type="hidden" value="1"></td>
<td class="def " sel="text">10M
<input type="hidden" value="10M"></td>
<td class="def " sel="select">Deaktiviert
<input type="hidden" value="2"></td>
<td class="def firstCol" sel="text">9702
<input type="hidden" value="9702"></td>

<tr class="portID"><td class="def firstCol def_center"><input class="checkbox" type="checkbox" name="port7" rownumber="" value="checked" onclick="checkBoxOnclick();"></td>
<td class="def firstCol" sel="text">7
<input type="hidden" value="7"></td>
<td class="def " sel="text">Aktiv
<input type="hidden" value="Aktiv"></td>
<td class="def " sel="select">Auto
<input type="hidden" value="1"></td>
<td class="def " sel="text">1000M
<input type="hidden" value="1000M"></td>
<td class="def " sel="select">Deaktiviert
<input type="hidden" value="2"></td>
<td class="def firstCol" sel="text">9702
<input type="hidden" value="9702"></td>

<tr class="portID"><td class="def firstCol def_center"><input class="checkbox" type="checkbox" name="port8" rownumber="" value="checked" onclick="checkBoxOnclick();"></td>
<td class="def firstCol" sel="text">8
<input type="hidden" value="8"></td>
<td class="def " sel="text">Aktiv
<input type="hidden" value="Aktiv"></td>
<td class="def " sel="select">Auto
<input type="hidden" value="1"></td>
<td class="def " sel="text">1000M
<input type="hidden" value="1000M"></td>
<td class="def " sel="select">Deaktiviert
<input type="hidden" value="2"></td>
<td class="def firstCol" sel="text">9702
<input type="hidden" value="9702"></td>

</tr>
</table>
</td></tr>
<input type="hidden" name='hash' id='hash' value='c5a48d6ac7ad82a556188a6068548989'>
</table>
</td></tr>
</form>
<script>
var str = CreateButtons('button','Aktualisieren','refreshForm()','btn_Refresh','on');
str += CreateButtons('button','Übernehmen','javaScript:void(0)','btn_Apply','off');
PaintButtons(str);
</script>
</head>
</html>
```
port_statistics.htm
```
<!DOCTYPE html>
<html>
<head>
<title>Port Statistics</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<link rel="stylesheet" type="text/css" href="/style.css?v3.e">
<script  src="frame.js?v3.e" type="text/javascript"></script>
<script  src="function.js?v3.e" type="text/javascript"></script>
</head>
<body onload="initTableCss();counter()">
<form method="post" action="portStatistics.cgi">
<input type="hidden" name="clearCounters" id="clearCounters" value="">
<input type="hidden" name='hash' id='hash' value='c5a48d6ac7ad82a556188a6068548989'>
</form>
<form method="get" action="portStatistics.cgi">
<table class="detailsAreaContainer">
<tr>
<td>
<table class="tableStyle">
<tr>
<script>tbhdrTable('Portstatistik','portStatistics')</script>
</tr>
<tr><td class="topTitleBottomBar" colspan="2"></td></tr>
<tr><td class="paddingTableBody" colspan="2"><table class="tableStyle" id="tbl2" style='width:745px;'>
<tr>
<tr>
<td class="def_TH">Port</td>
<td class="def_TH spacer30Percent">Empfangene Bytes</td>
<td class="def_TH spacer30Percent">Gesendete Bytes</td>
<td class="def_TH spacer30Percent">Pakete mit CRC-Fehlern</td>


<tr class="portID" name="portID">
<td class="def firstCol" sel="text">1</td>
<td class="def" sel="text"></td>
<input type='hidden' name='rxPkt' value='00000000'>
<td class="def" sel="text"></td>
<input type='hidden' name='txpkt' value='00000000'>
<td class="def" sel="text"></td>
<input type='hidden' name='crcPkt' value='00000000'>

<tr class="portID" name="portID">
<td class="def firstCol" sel="text">2</td>
<td class="def" sel="text"></td>
<input type='hidden' name='rxPkt' value='00000000'>
<td class="def" sel="text"></td>
<input type='hidden' name='txpkt' value='00000000'>
<td class="def" sel="text"></td>
<input type='hidden' name='crcPkt' value='00000000'>

<tr class="portID" name="portID">
<td class="def firstCol" sel="text">3</td>
<td class="def" sel="text"></td>
<input type='hidden' name='rxPkt' value='00000000'>
<td class="def" sel="text"></td>
<input type='hidden' name='txpkt' value='00000000'>
<td class="def" sel="text"></td>
<input type='hidden' name='crcPkt' value='00000000'>

<tr class="portID" name="portID">
<td class="def firstCol" sel="text">4</td>
<td class="def" sel="text"></td>
<input type='hidden' name='rxPkt' value='00000000'>
<td class="def" sel="text"></td>
<input type='hidden' name='txpkt' value='00000000'>
<td class="def" sel="text"></td>
<input type='hidden' name='crcPkt' value='00000000'>

<tr class="portID" name="portID">
<td class="def firstCol" sel="text">5</td>
<td class="def" sel="text"></td>
<input type='hidden' name='rxPkt' value='00000000'>
<td class="def" sel="text"></td>
<input type='hidden' name='txpkt' value='0021C9F8'>
<td class="def" sel="text"></td>
<input type='hidden' name='crcPkt' value='00000000'>

<tr class="portID" name="portID">
<td class="def firstCol" sel="text">6</td>
<td class="def" sel="text"></td>
<input type='hidden' name='rxPkt' value='00000000'>
<td class="def" sel="text"></td>
<input type='hidden' name='txpkt' value='0021C9F8'>
<td class="def" sel="text"></td>
<input type='hidden' name='crcPkt' value='00000000'>

<tr class="portID" name="portID">
<td class="def firstCol" sel="text">7</td>
<td class="def" sel="text"></td>
<input type='hidden' name='rxPkt' value='0016A15C'>
<td class="def" sel="text"></td>
<input type='hidden' name='txpkt' value='006A6076'>
<td class="def" sel="text"></td>
<input type='hidden' name='crcPkt' value='00000000'>

<tr class="portID" name="portID">
<td class="def firstCol" sel="text">8</td>
<td class="def" sel="text"></td>
<input type='hidden' name='rxPkt' value='006B6FE4'>
<td class="def" sel="text"></td>
<input type='hidden' name='txpkt' value='0019BF6B'>
<td class="def" sel="text"></td>
<input type='hidden' name='crcPkt' value='00000000'>


</tr>

</table>
</td></tr>
</table>
</td></tr>
</form>
<script>
var str = CreateButtons('button','Zähler zurücksetzen','submitClearCounters()','btn_Cancel','on');
str += CreateButtons('button','Aktualisieren','submitForm()','btn_Refresh','on');
PaintButtons(str);
</script>
</body>
</html>
```

**Comment by foxey** [comment]
Ah, my bad. I wasn't aware that there was a PE version as well. That one is not yet in the list of supported models. Is it a PoE switch as well?

**Comment by foxey** [comment]
I'm currently working on refactoring to make testing easier to integrate. Once that's finished, I'll be able to add additional models more easily. I'll keep you posted.

**Comment by rice1204** [comment]
> Ah, my bad. I wasn't aware that there was a PE version as well. That one is not yet in the list of supported models. Is it a PoE switch as well?

Yes, GS108PEv3 is a PoE switch too. I would eagerly help test :)

**Comment by Megachip** [comment]
> Ah, my bad. I wasn't aware that there was a PE version as well. That one is not yet in the list of supported models. Is it a PoE switch as well?

4port poe. But there are no options or stats in webinterface. So I would expect GS108v3 would work, except the different name

**Comment by foxey** [comment]
@Megachip is this issue still relevant?

If so, could you install the latest pre-release of the py-netgear-plus library in a Python virtual environment and run this test for me:

```bash
python -mvenv venv
. ./venv/bin/activate  # or in Windows: \venv\Scripts\activate.bat
pip install py-netgear-plus==v0.4.2rc4
ngp-cli -dv identify SWITCH_IP_ADDRESS
ngp-cli -dvP YOUR_PASSWORD login SWITCH_IP_ADDRESS
ngp-cli -dv save
ngp-cli -dv collect
ngp-cli -dv logout
```
Please share the debug logging here and upload a zipfile with the pages collected in the `pages` folder.

**Comment by foxey** [comment]
@Megachip I just released v0.7.5. Can you update the integration through HACS and let me know if the switch is properly supported now?
