### ISSUE TITLE
Side effects when switching POE port power on GS308EP

### ISSUE THREAD

**Issue by foxey** [ckarrie/ha-netgear-plus#27]
There are some unwanted side effects caused by enabling/disabling the POE Port Power using this integration:

Initial settings:

```
| Port Priority         | Low             |
| Power Limit Type      | User            |
| Power Limit (W)       | 30.0            |
| Detection Type        | IEEE 802        |
| Longer Detection Time | Disable         |
```
Settings after switching off and on again:

```
| Port Priority         | Low             |
| Power Limit Type      | None            |
| Power Limit (W)       | 16.2            |
| Detection Type        |                 |
| Longer Detection Time | Get Value Fault |
```

The switch probably expects a full set of data in the posted form and overwrites the missing attributes with default/empty values. A way to solve this is to fetch the form first, copy the current settings and only change the port power value before posting back the entire form.

**Comment by vanrace** [comment]
I can confirm this happens with the GS308EPP as well. Happy to support testing

**Comment by foxey** [comment]
@vanrace Release v0.7.0 should now use sane defaults. I've not yet fixed parsing the config page, storing the current settings and translating those to the equivalent form fields for the POST request.
Please test the new version and let me know if this fits your needs.

**Comment by vanrace** [comment]
@foxey, sorry for my late reply and thanks for sharing. Unfortunately this version does not load. It looks like my model (GS308EPP) does not get recognized. 

Log from HA: 

`Logger: homeassistant.config_entries
Source: config_entries.py:640
First occurred: January 5, 2025 at 17:57:22 (1 occurrences)
Last logged: January 5, 2025 at 17:57:22

Error setting up entry GS308EPP 172.16.0.212 for netgear_plus
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/netgear_plus/__init__.py", line 38, in async_setup_entry
    if not await gs_switch.async_setup():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/netgear_plus/netgear_switch.py", line 80, in async_setup
    if not await self.hass.async_add_executor_job(self._setup):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/netgear_plus/netgear_switch.py", line 62, in _setup
    self.api = get_api(host=self._host, password=self._password)
               ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/netgear_plus/netgear_switch.py", line 30, in get_api
    api.autodetect_model()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/py_netgear_plus/__init__.py", line 195, in autodetect_model
    raise SwitchModelNotDetectedError
py_netgear_plus.SwitchModelNotDetectedError`

**Comment by foxey** [comment]
@vanrace Yes, I discovered that as well, a stupid regression. I'm currently creating a pre-release with a fix so you can test it out.

**Comment by foxey** [comment]
@vanrace Could you install https://github.com/ckarrie/ha-netgear-plus/releases/tag/v0.7.1pre3 manually and let me know if the switch is detected again?

**Comment by foxey** [comment]
Please wait with testing, I just realized that I forgot to update the parser.

**Comment by foxey** [comment]
Please wait with testing, I just realized that I forgot to update the parser.

**Comment by vanrace** [comment]
One step further:

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/netgear_plus/__init__.py", line 38, in async_setup_entry
    if not await gs_switch.async_setup():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/netgear_plus/netgear_switch.py", line 80, in async_setup
    if not await self.hass.async_add_executor_job(self._setup):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/netgear_plus/netgear_switch.py", line 62, in _setup
    self.api = get_api(host=self._host, password=self._password)
               ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/netgear_plus/netgear_switch.py", line 30, in get_api
    api.autodetect_model()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/py_netgear_plus/__init__.py", line 157, in autodetect_model
    self._page_parser = create_page_parser(
                        ~~~~~~~~~~~~~~~~~~^
        self.switch_model.MODEL_NAME
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/py_netgear_plus/parsers.py", line 27, in create_page_parser
    raise NetgearPlusPageParserModelNotSupportedError(message)
py_netgear_plus.parsers.NetgearPlusPageParserModelNotSupportedError: Model GS308EPP not supported by the parser. `

**Comment by vanrace** [comment]
It’s running! Did not do any further testing yet.

**Comment by foxey** [comment]
@vanrace Great! At last! In order to prevent too many iterations in the future, could you install the python library, run the following commands and add a zipfile of the `pages` folder to this issue? I'll add the model to the unit test suite.

```bash
virtualenv venv
. ./venv/bin/activate
pip install py-netgear-plus==0.3.1rc6
ngp-cli -P P4ssw0rd login 192.168.x.y
ngp-cli collect
ngp-cli logout
```

**Comment by vanrace** [comment]
That is a bit above my abilities I am afraid. Happy to help but would need a bit more guidance. More a windows guy I am afraid… running it on a rpi4

**Comment by foxey** [comment]
@vanrace No problem. Let me think about your suggestion. It would imply to add a switch in the integration to explicitly turn it on as I don't want to clutter everyone's HA installations with downloaded files.
BTW as a Windows guy, you can do Python as well. Have a look [here](https://learn.microsoft.com/en-us/windows/python/beginners) if you're interested. For the virtual environment, type `python -m venv venv` and to activate `venv\bin\activate.bat`. The rest is the same as above.

**Comment by vanrace** [comment]
Hi @foxey (fellow dutchey! ;-) ) Thanks for the pointers! Installed Python 3.13 and started the virtual environment (directory structure is created). I can only make it accept my password and run without any messages when I put double quotes around it, without I get: 

`'XXXXXXX' is not recognized as an internal or external command,
operable program or batch file.`

with the double quotes it still does not seem to authenticate however, so I am probably still doing it wrong: 

`(venv) C:\Users\peter>ngp-cli -P "XXXXXXXXXXXX" login 172.16.0.212

(venv) C:\Users\peter>ngp-cli collect
[NetgearSwitchConnector.handle_soft_authentication_failure] [IP: 172.16.0.212] Response from switch: "Invalid Password"
Traceback (most recent call last):
  File "C:\Users\peter\venv\Lib\site-packages\py_netgear_plus\__init__.py", line 345, in fetch_page
    response = self._page_fetcher.request(method, url, data)
  File "C:\Users\peter\venv\Lib\site-packages\py_netgear_plus\fetcher.py", line 232, in request
    raise NotLoggedInError
py_netgear_plus.fetcher.NotLoggedInError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\peter\venv\Scripts\ngp-cli.exe\__main__.py", line 7, in <module>
    sys.exit(main())
             ~~~~^^
  File "C:\Users\peter\venv\Lib\site-packages\py_netgear_plus\ngp_cli.py", line 197, in main
    command_functions[args.command](connector, args)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\peter\venv\Lib\site-packages\py_netgear_plus\ngp_cli.py", line 224, in collect_command
    connector.save_pages(path)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\peter\venv\Lib\site-packages\py_netgear_plus\__init__.py", line 766, in save_pages
    response = self.fetch_page_from_templates([template])
  File "C:\Users\peter\venv\Lib\site-packages\py_netgear_plus\__init__.py", line 373, in fetch_page_from_templates
    response = self.fetch_page(method, url, data)
  File "C:\Users\peter\venv\Lib\site-packages\py_netgear_plus\__init__.py", line 351, in fetch_page
    raise LoginFailedError(message) from error
py_netgear_plus.fetcher.LoginFailedError: Not logged in and unable to login.

(venv) C:\Users\peter>`

Any ideas what I am doing wrong here?

**Comment by foxey** [comment]
@vanrace you're not doing anything wrong. It's yet another bug in my software. I normally use the CLI with an environment variable NETGEAR_PLUS_PASSWORD to prevent that I have to use the -P option every time I login. During the 'collect' action, i need one page unauthenticated, so I logout. When the environment variable is set, that is not a problem, as I automatically login again for the next page I download. When the login has been done with the `-P` option, the password is not available during the 'collect' action and the re-login fails. My bad. I will fix this and release (yet) another version.

**Comment by vanrace** [comment]
**_Success!_** 

The environment variable approach works in Windows. The final challenge was I had the ^ character in my password which created complications. So changed my password to a simpeler one and applied the environment variable and hey presto, works. Thanks for your support! 

[[pages GS308EPP.zip](https://github.com/user-attachments/files/18346089/pages.GS308EPP.zip)](url)

**Comment by vanrace** [comment]
Hi @foxey. Thanks for the heads up, I removed the zip. and nice the pages are in your tests! Do you want an update when a new firmware version comes out?

I am not sure I understand what you want me to test. I had the login block when retrieving the pages and not actively logging off afterwards. Should I test that again?

**Comment by foxey** [comment]
Hi @vanrace,

I'm about to release v0.4.0 of the library to use in a new version of the HA integration. If you would be so kind to test the following scenario and share the output:

```bash
virtualenv venv
. ./venv/bin/activate
pip install py-netgear-plus==0.4.0rc6
ngp-cli -dvP P4ssw0rd login 192.168.x.y
ngp-cli -dv collect
ngp-cli -dv logout
```

You have to change P4ssw0rd and th ip address to match your config.

Thanks!

**Comment by vanrace** [comment]
The login command keeps locking up my router. I tried multiple times (with enough time in-between): 

`Enabling debug mode.
DEBUG:py_netgear_plus.parsers:PageParser object initialized.
DEBUG:py_netgear_plus:[NetgearSwitchConnector] instance (v0.4.0rc6) created for IP=172.16.0.212
DEBUG:py_netgear_plus:[NetgearSwitchConnector] DEBUG logging enabled. Your logs may contain sensitve information like passwords or session cookies. Do not use in production.
DEBUG:py_netgear_plus:[NetgearSwitchConnector.autodetect_model] called for IP=172.16.0.212
DEBUG:py_netgear_plus.fetcher:[PageFetcher.request] calling GET http://172.16.0.212/login.cgi without cookie with params=None, allow_redirects=False, timeout=15
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 172.16.0.212:80
DEBUG:urllib3.connectionpool:http://172.16.0.212:80 "GET /login.cgi HTTP/1.1" 200 None
DEBUG:py_netgear_plus.parsers:[PageParser.parse_login_switchinfo_tag] DIV with class 'switchInfo' not found.
DEBUG:py_netgear_plus.parsers:[PageParser.parse_login_switchinfo_tag] DIV with class 'switchInfo' not found.
INFO:py_netgear_plus:[NetgearSwitchConnector.autodetect_model] found GS308EPP switch.
DEBUG:py_netgear_plus.parsers:GS308EPP object initialized.
DEBUG:py_netgear_plus.fetcher:[PageFetcher.check_login_url] calling request for GET http://172.16.0.212/login.cgi with allow_directs=False, timeout=15
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 172.16.0.212:80
DEBUG:urllib3.connectionpool:http://172.16.0.212:80 "GET /login.cgi HTTP/1.1" 200 None
DEBUG:py_netgear_plus:[NetgearSwitchConnector.get_login_cookie] using password crypted with rand=1425622205
DEBUG:py_netgear_plus.fetcher:[PageFetcher.get_login_page] calling request for POST http://172.16.0.212/login.cgi with data={'password': 'xxxxxxxxxxxxxxxxxx'}, allow_redirects=True, timeout=15
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 172.16.0.212:80
DEBUG:urllib3.connectionpool:http://172.16.0.212:80 "POST /login.cgi HTTP/1.1" 200 None
DEBUG:py_netgear_plus:[NetgearSwitchConnector.get_login_cookie] looking for cookies: SID
DEBUG:py_netgear_plus.parsers:[PageParser.parse_gambit_tag] Gambit INPUT element not found.
DEBUG:py_netgear_plus:[NetgearSwitchConnector.get_login_cookie] No Gambit tag or valid cookie found.
WARNING:py_netgear_plus:[NetgearSwitchConnector.handle_soft_authentication_failure] [IP: 172.16.0.212] Response from switch: "Your account is temporarily locked. Try again in @5@ minutes."`

If you want we can connect 1 on 1 to dig deeper if you think that will be more efficient?

**Comment by foxey** [comment]
@vanrace Thanks a lot. From what I can quickly see it's working as expected now. The logout step is superfluous now (as the output of the collect command already states, it logs out before collecting the last page). The IP address is indeed not correct. It is not collected from the web pages and therefore the unit test fails if I don't replace it with a standard value.

I'll use the rc10 prerelease for a new version of the HA integration. If you can let me know if that one works for you, I think we're good to go for an official new release in HACS.

**Comment by vanrace** [comment]
@foxey awesome, let me know when I can test

**Comment by foxey** [comment]
@vanrace There's a new library version out (0.4.0rc11) and a pre-release of the HACS integration (0.7.2rc0). Let me know how you fare!

**Comment by vanrace** [comment]
Did not have time for a real test but confirmed it loads and shows realistic values!

**Comment by foxey** [comment]
Closed with release 0.7.2
